services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - type: volume
        source: static_volume
        target: /portfolio/staticfiles
      - type: volume
        source: media_volume
        target: /portfolio/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - type: volume
        source: static_volume
        target: /portfolio/staticfiles
      - type: volume
        source: media_volume
        target: /portfolio/media


volumes:
  static_volume:
  media_volume:
  postgres_data:

