# Generated by Django 5.1.4 on 2024-12-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_experience_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='working_time',
            field=models.CharField(max_length=100),
        ),
    ]
