# Generated by Django 5.1.4 on 2024-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=models.FloatField(),
        ),
    ]
